### ISSUE TITLE
[Question] Unable to print with star-prnt on TSP100III

### ISSUE THREAD

**Issue by jay-babu** [NielsLeenheer/StarPrntEncoder#2]
i have to support multiple devices and i was able to get this working on an epson printer using the esc mode however when trying to print on a star printer using star-prnt language, it does not work. i am printing from a mac using chrome. how can i debug why it is not working?

**Comment by jay-babu** [comment]
```
    let encoder = new ThermalPrinterEncoder({
      language: "star-prnt",
    });

    let result = encoder
      .text("The quick brown fox jumps over the lazy dog")
      .text("The quick brown fox jumps over the lazy dog")
      .text("The quick brown fox jumps over the lazy dog")
      .text("The quick brown fox jumps over the lazy dog")
      .text("The quick brown fox jumps over the lazy dog")
      .text("The quick brown fox jumps over the lazy dog")
      .text("The quick brown fox jumps over the lazy dog")
      .text("The quick brown fox jumps over the lazy dog")
      .text("The quick brown fox jumps over the lazy dog")
      .cut()
      .encode();

    console.log(result);

    const receiptPrinter = new WebUSBReceiptPrinter();

    await receiptPrinter.connect();

    await receiptPrinter.print(result);

    await receiptPrinter.disconnect();
```

**Comment by jay-babu** [comment]
i had added initialize then  removed it to test. i also had codepage set to auto

**Comment by NielsLeenheer** [comment]
The library has been tested on and should work on a TSP100III. 

What is happening exactly? Does it output anything? 

Also, if it does print, but it looks weird, one thing you could try is to see how the dip-switches on the bottom of the printer are configured. It is possible the printer is set up to use ESC/POS instead of StarPrnt.

**Comment by NielsLeenheer** [comment]
Okay, I have more information about this. 

The TSP100 series itself does not support either Star Line Mode or StarPRNT, used by this library. It uses Star Graphics Mode internally and is not compatible with StarPrntEncoder. 

The Windows printer driver does include an automatic software based simulator for Star Line. So if you print on Windows using the printer driver it will work. You can do this with the build in serial port emulator and WebSerialReceiptPrinter.

So, this printer is not compatible with WebUSBReceiptPrinter on Mac.
